\set ON_ERROR_STOP on
begin;
create function pg_temp.assert_true(condition boolean,message text) returns void language plpgsql as $$ begin if condition is distinct from true then raise exception 'FAILED: %',message; end if; raise notice 'PASS: %',message; end $$;
create function pg_temp.learning_document(wid uuid) returns jsonb language sql as $$ select jsonb_build_object('schemaVersion',1,'workspaceId',wid,'revision',0,'updatedAt',now(),'subjects','[]'::jsonb,'projects','[]'::jsonb,'tasks','[]'::jsonb,'plannedSessions','[]'::jsonb,'focusSessions','[]'::jsonb,'journal','[]'::jsonb,'events','[]'::jsonb,'noteSheets','[]'::jsonb,'flashcardDecks','[]'::jsonb,'flashcards','[]'::jsonb,'preferences','{"customTheme":null,"savedLayouts":[],"accentColor":"#123456","background":{"kind":"none","preset":"aurora","image":null,"overlay":70,"blur":0}}'::jsonb,'timer','{"status":"idle","phase":"focus","cycleCount":0}'::jsonb) $$;
select set_config('request.jwt.claim.role','service_role',true);
insert into auth.users(id,email,email_confirmed_at) values('11111111-1111-4111-8111-111111111111','alice@example.test',now()),('22222222-2222-4222-8222-222222222222','bob@example.test',now()),('33333333-3333-4333-8333-333333333333','viewer@example.test',now());
select set_config('test.alice',public.folia_onboard('11111111-1111-4111-8111-111111111111')::text,true);
select set_config('test.bob',public.folia_onboard('22222222-2222-4222-8222-222222222222')::text,true);
select set_config('test.org',(public.folia_manage_workspace('11111111-1111-4111-8111-111111111111','create',null,'{"name":"Learning team"}')->>'workspaceId'),true);

do $$ declare alice uuid:='11111111-1111-4111-8111-111111111111'; wid uuid:=current_setting('test.alice')::uuid; sid uuid:=gen_random_uuid(); doc jsonb; note jsonb; deck jsonb; card jsonb; focus jsonb; legacy jsonb; prefs jsonb; result jsonb; operation uuid:=gen_random_uuid(); old_operation uuid:=gen_random_uuid(); version_now bigint:=0;
begin
  doc:=pg_temp.learning_document(wid);
  legacy:=jsonb_set(doc-array['noteSheets','flashcardDecks','flashcards'],'{preferences}',(doc->'preferences')-array['background','accentColor']);
  -- Model a receipt created by the pre-upgrade implementation with no request_hash.
  perform private.commit_document_v1(alice,wid,legacy,0,old_operation); version_now:=1;
  result:=public.folia_commit_document(alice,wid,legacy,0,old_operation);
  perform pg_temp.assert_true((result->>'replayed')::boolean and result->>'committedVersion'='1','Operations saved before migration remain replayable');
  perform pg_temp.assert_true(not (public.workspace_entitlements(wid)->'features'->>'backgrounds')::boolean and not (public.workspace_entitlements(wid)->'features'->>'flashcards')::boolean,'Free has no paid background or flashcard flags');
  note:=jsonb_build_object('id',gen_random_uuid(),'workspaceId',wid,'userId',alice,'title','What I learned','content','A useful observation','kind','note','revisions','[]'::jsonb,'createdAt',now(),'updatedAt',now());
  doc:=jsonb_set(doc,'{events}',jsonb_build_array(jsonb_build_object('id',gen_random_uuid(),'workspaceId',wid,'userId',alice,'type','note_created','timestamp',now(),'details','Created a note')));
  doc:=jsonb_set(doc,'{noteSheets}',jsonb_build_array(note));
  perform public.folia_commit_document(alice,wid,doc,version_now,gen_random_uuid()); version_now:=version_now+1;
  perform pg_temp.assert_true((select count(*)=1 from public.note_sheets where workspace_id=wid),'Free note sheets have a normalized projection');
  perform pg_temp.assert_true((select data->>'accentColor'='#123456' from public.preferences where workspace_id=wid and user_id=alice),'Free custom accent saves without paid entitlement');
  begin perform public.folia_commit_document(alice,wid,jsonb_set(doc,'{preferences,background,kind}','"preset"'),version_now,gen_random_uuid()); raise exception 'Unpaid background saved'; exception when insufficient_privilege then raise notice 'PASS: Document background writes require a paid plan'; end;
  begin perform public.folia_save_preferences(alice,wid,jsonb_set(doc->'preferences','{background,kind}','"preset"'),version_now,gen_random_uuid()); raise exception 'Unpaid preference background saved'; exception when insufficient_privilege then raise notice 'PASS: Private preference background writes require a paid plan'; end;
  begin perform public.folia_save_preferences(alice,wid,jsonb_set(doc->'preferences','{accentColor}','"red"'),version_now,gen_random_uuid()); raise exception 'Invalid accent saved'; exception when invalid_parameter_value then raise notice 'PASS: Invalid custom accent is rejected'; end;
  begin perform public.folia_commit_document(alice,wid,jsonb_set(doc,'{noteSheets,0,content}','"New content"'),version_now,gen_random_uuid()); raise exception 'Note revision discarded'; exception when check_violation then raise notice 'PASS: Editing notes must append previous title and content'; end;
  doc:=jsonb_set(doc,'{noteSheets,0}',note||jsonb_build_object('content','Refined observation','revisions',jsonb_build_array(jsonb_build_object('title',note->>'title','content',note->>'content','editedAt',now()))));
  perform public.folia_commit_document(alice,wid,doc,version_now,gen_random_uuid()); version_now:=version_now+1;
  perform pg_temp.assert_true((select payload->'revisions'->0->>'content'='A useful observation' from public.note_sheets where workspace_id=wid),'Free note edits preserve revision history');
  deck:=jsonb_build_object('id',gen_random_uuid(),'workspaceId',wid,'userId',alice,'title','Study deck','description','','createdAt',now(),'updatedAt',now());
  card:=jsonb_build_object('id',gen_random_uuid(),'workspaceId',wid,'userId',alice,'deckId',deck->>'id','front','Question','back','Answer','createdAt',now(),'updatedAt',now());
  begin perform public.folia_commit_document(alice,wid,jsonb_set(doc,'{flashcardDecks}',jsonb_build_array(deck)),version_now,gen_random_uuid()); raise exception 'Unpaid deck created'; exception when insufficient_privilege then raise notice 'PASS: Creating a flashcard deck requires paid entitlement'; end;
  insert into public.workspace_subscriptions(workspace_id,tier,paid_tier,status,paid_through) values(wid,'pro','pro','active',now()+interval '30 days');
  perform pg_temp.assert_true((public.workspace_entitlements(wid)->'features'->>'backgrounds')::boolean and (public.workspace_entitlements(wid)->'features'->>'flashcards')::boolean,'Trusted paid Pro grants both new features');
  doc:=jsonb_set(jsonb_set(jsonb_set(doc,'{flashcardDecks}',jsonb_build_array(deck)),'{flashcards}',jsonb_build_array(card)),'{preferences,background,kind}','"preset"');
  doc:=jsonb_set(doc,'{subjects}',jsonb_build_array(jsonb_build_object('id',sid,'name','Completed topic','archived',false,'completedAt','2026-09-10T09:00:00Z')));
  perform public.folia_commit_document(alice,wid,doc,version_now,gen_random_uuid()); version_now:=version_now+1;
  perform pg_temp.assert_true((select count(*)=1 from public.flashcards where workspace_id=wid) and (select count(*)=1 from public.flashcard_decks where workspace_id=wid),'Paid deck and cards commit together');
  perform pg_temp.assert_true((select completed_at='2026-09-10T09:00:00Z'::timestamptz from public.subjects where workspace_id=wid and id=sid),'Subject completion is projected into a timestamp');
  begin perform public.folia_commit_document(alice,wid,jsonb_set(doc,'{flashcards,0,deckId}',to_jsonb(gen_random_uuid())),version_now,gen_random_uuid()); raise exception 'Unknown deck linked'; exception when check_violation then raise notice 'PASS: Flashcards must reference an existing workspace deck'; end;
  begin perform public.folia_commit_document(alice,wid,jsonb_set(doc,'{noteSheets,0,workspaceId}',to_jsonb(gen_random_uuid())),version_now,gen_random_uuid()); raise exception 'Wrong workspace note saved'; exception when check_violation then raise notice 'PASS: Learning records cannot claim another workspace'; end;
  begin perform public.folia_commit_document(alice,wid,jsonb_set(doc,'{noteSheets,0,subjectId}',to_jsonb(gen_random_uuid())),version_now,gen_random_uuid()); raise exception 'Unknown subject linked'; exception when check_violation then raise notice 'PASS: Learning subject references stay inside workspace'; end;
  focus:=jsonb_build_object('id',gen_random_uuid(),'workspaceId',wid,'userId',alice,'phase','focus','status','completed','startedAt','2026-09-10T08:00:00Z','endedAt','2026-09-10T08:25:00Z','durationMinutes',25,'actualSeconds',1500,'context',jsonb_build_object('workspaceId',wid,'userId',alice,'subjectId',sid));
  doc:=jsonb_set(doc,'{focusSessions}',jsonb_build_array(focus));
  doc:=jsonb_set(doc,'{noteSheets,0}',doc->'noteSheets'->0||jsonb_build_object('sessionId',focus->>'id','subjectId',sid,'kind','session_reflection'));
  perform public.folia_commit_document(alice,wid,doc,version_now,gen_random_uuid()); version_now:=version_now+1;
  perform pg_temp.assert_true((select session_id=(focus->>'id')::uuid from public.note_sheets where workspace_id=wid),'Reflection note and completed focus may commit atomically');
  begin perform public.folia_commit_document(alice,wid,jsonb_set(doc,'{noteSheets,0,sessionId}',to_jsonb(gen_random_uuid())),version_now,gen_random_uuid()); raise exception 'Unknown focus linked'; exception when check_violation then raise notice 'PASS: Reflection cannot reference a missing focus session'; end;
  prefs:=jsonb_set(doc->'preferences','{background}', '{"kind":"image","preset":"aurora","image":"data:image/png;base64,aGVsbG8=","overlay":75,"blur":2}');
  perform public.folia_save_preferences(alice,wid,prefs,version_now,gen_random_uuid()); version_now:=version_now+1;
  perform pg_temp.assert_true((select data->'background'->>'kind'='image' from public.preferences where workspace_id=wid and user_id=alice),'Paid image background is kept in private preferences');
  begin perform public.folia_save_preferences(alice,wid,jsonb_set(prefs,'{background,image}','"data:image/svg+xml;base64,aGVsbG8="'),version_now,gen_random_uuid()); raise exception 'SVG saved'; exception when invalid_parameter_value then raise notice 'PASS: Backgrounds reject SVG and remote URL formats'; end;
  begin perform public.folia_save_preferences(alice,wid,jsonb_set(prefs,'{background,image}',to_jsonb('data:image/png;base64,'||repeat('A',350000))),version_now,gen_random_uuid()); raise exception 'Oversize image saved'; exception when invalid_parameter_value then raise notice 'PASS: Background image payload is bounded'; end;
  begin perform public.folia_save_preferences(alice,wid,jsonb_set(prefs,'{background,kind}','null'),version_now,gen_random_uuid()); raise exception 'Null kind saved'; exception when invalid_parameter_value then raise notice 'PASS: Invalid background kinds cannot exploit null comparisons'; end;
  legacy:=doc-array['noteSheets','flashcardDecks','flashcards'];
  legacy:=jsonb_set(jsonb_set(legacy,'{preferences}',(doc->'preferences')-array['background','accentColor']),'{subjects,0}',(doc->'subjects'->0)-'completedAt');
  legacy:=jsonb_set(legacy,'{events}','[]');
  perform public.folia_commit_document(alice,wid,legacy,version_now,operation); version_now:=version_now+1;
  perform pg_temp.assert_true((select jsonb_array_length(data->'noteSheets')=1 and jsonb_array_length(data->'flashcards')=1 from public.workspace_documents where workspace_id=wid),'Older client writes preserve omitted learning collections');
  perform pg_temp.assert_true((select completed_at is not null from public.subjects where workspace_id=wid and id=sid),'Older client writes preserve subject completion');
  perform pg_temp.assert_true((select data->'background'->>'kind'='image' and data->>'accentColor'='#123456' from public.preferences where workspace_id=wid and user_id=alice),'Older document writes preserve private background and accent');
  perform pg_temp.assert_true((select jsonb_array_length(data->'events')=1 from public.workspace_documents where workspace_id=wid),'Legacy writes preserve learning events hidden from old strict schemas');
  prefs:=jsonb_set(prefs,'{accentColor}','"#654321"');
  prefs:=prefs||'{"accent":"blurple"}'::jsonb;
  perform public.folia_save_preferences(alice,wid,prefs,version_now,gen_random_uuid()); version_now:=version_now+1;
  result:=public.folia_commit_document(alice,wid,legacy,0,operation);
  perform pg_temp.assert_true((result->>'replayed')::boolean and (result->>'committedVersion')::bigint=version_now-1,'Legacy retry stays idempotent after another private preference write');
  perform pg_temp.assert_true((select data->>'accentColor'='#654321' from public.preferences where workspace_id=wid and user_id=alice),'Replayed legacy write cannot overwrite newer preferences');
  update public.workspace_subscriptions set paid_through=now()-interval '1 second',status='canceled' where workspace_id=wid;
  doc:=jsonb_set(doc,'{preferences}',prefs);
  perform public.folia_commit_document(alice,wid,doc,version_now,gen_random_uuid()); version_now:=version_now+1;
  perform pg_temp.assert_true((select count(*)=1 from public.flashcards where workspace_id=wid),'Downgrade retains existing cards during normal sync');
  begin perform public.folia_commit_document(alice,wid,jsonb_set(doc,'{flashcards,0,front}','"Changed question"'),version_now,gen_random_uuid()); raise exception 'Unpaid card edit saved'; exception when insufficient_privilege then raise notice 'PASS: Downgrade blocks changing existing flashcards'; end;
  begin perform public.folia_save_preferences(alice,wid,jsonb_set(prefs,'{background,blur}','3'),version_now,gen_random_uuid()); raise exception 'Unpaid background edit saved'; exception when insufficient_privilege then raise notice 'PASS: Downgrade blocks changing active premium backgrounds'; end;
  perform public.folia_save_preferences(alice,wid,prefs-array['background','accentColor'],version_now,gen_random_uuid()); version_now:=version_now+1;
  perform pg_temp.assert_true((select data->'background'->>'kind'='image' from public.preferences where workspace_id=wid and user_id=alice),'Legacy preference writes retain premium background after downgrade');
  perform public.folia_save_preferences(alice,wid,(prefs-array['background','accentColor'])||'{"accent":"blue"}'::jsonb,version_now,gen_random_uuid()); version_now:=version_now+1;
  perform pg_temp.assert_true((select data->>'accent'='blurple' from public.preferences where workspace_id=wid and user_id=alice),'Old accent fallback cannot silently replace a newer saved accent');
  prefs:=jsonb_set(prefs,'{background,kind}','"none"');
  perform public.folia_save_preferences(alice,wid,prefs,version_now,gen_random_uuid()); version_now:=version_now+1;
  perform pg_temp.assert_true((select data->'background'->>'kind'='none' from public.preferences where workspace_id=wid and user_id=alice),'Downgrade allows resetting background without losing uploaded image bytes');
  doc:=jsonb_set(jsonb_set(jsonb_set(doc,'{flashcards}','[]'),'{flashcardDecks}','[]'),'{preferences}',prefs);
  doc:=jsonb_set(doc,'{subjects,0}',(doc->'subjects'->0)-'completedAt');
  perform public.folia_commit_document(alice,wid,doc,version_now,gen_random_uuid()); version_now:=version_now+1;
  perform pg_temp.assert_true((select count(*)=0 from public.flashcards where workspace_id=wid) and (select count(*)=0 from public.flashcard_decks where workspace_id=wid),'Downgrade allows deliberate deck and card removal');
  perform pg_temp.assert_true((select completed_at is null from public.subjects where workspace_id=wid and id=sid),'Modern clients can deliberately reopen a completed subject');
  perform pg_temp.assert_true(not (select data ? 'preferences' from public.workspace_documents where workspace_id=wid),'Personal background bytes never enter shared workspace JSON');
end $$;

do $$ declare alice uuid:='11111111-1111-4111-8111-111111111111'; bob uuid:='22222222-2222-4222-8222-222222222222'; org uuid:=current_setting('test.org')::uuid; doc jsonb; note jsonb; deck jsonb; card jsonb; prefs jsonb;
begin
  insert into public.workspace_memberships(workspace_id,user_id,role) values(org,bob,'member'),(org,'33333333-3333-4333-8333-333333333333','viewer');
  insert into public.workspace_subscriptions(workspace_id,tier,paid_tier,status,paid_through) values(org,'team','team','active',now()+interval '30 days');
  perform pg_temp.assert_true((public.workspace_entitlements(org)->'features'->>'backgrounds')::boolean and (public.workspace_entitlements(org)->'features'->>'flashcards')::boolean,'Team includes Pro background and flashcard features');
  doc:=pg_temp.learning_document(org);
  note:=jsonb_build_object('id',gen_random_uuid(),'workspaceId',org,'userId',bob,'title','Bob notes','content','Shared reading','kind','note','revisions','[]'::jsonb,'createdAt',now(),'updatedAt',now());
  deck:=jsonb_build_object('id',gen_random_uuid(),'workspaceId',org,'userId',bob,'title','Bob deck','description','','createdAt',now(),'updatedAt',now());
  card:=jsonb_build_object('id',gen_random_uuid(),'workspaceId',org,'userId',bob,'deckId',deck->>'id','front','Question','back','Answer','createdAt',now(),'updatedAt',now());
  doc:=doc||jsonb_build_object('noteSheets',jsonb_build_array(note),'flashcardDecks',jsonb_build_array(deck),'flashcards',jsonb_build_array(card));
  perform public.folia_commit_document(bob,org,doc,0,gen_random_uuid());
  begin perform public.folia_commit_document(alice,org,jsonb_set(doc,'{noteSheets}','[]'),1,gen_random_uuid()); raise exception 'Owner deleted member note'; exception when insufficient_privilege then raise notice 'PASS: Organization owner cannot delete another author note'; end;
  begin perform public.folia_commit_document(alice,org,jsonb_set(doc,'{flashcards,0,back}','"Changed answer"'),1,gen_random_uuid()); raise exception 'Owner edited member card'; exception when insufficient_privilege then raise notice 'PASS: Organization owner cannot edit another author flashcard'; end;
  begin perform public.folia_commit_document(bob,org,jsonb_set(doc,'{noteSheets,0,userId}',to_jsonb(alice)),1,gen_random_uuid()); raise exception 'Author transferred'; exception when insufficient_privilege then raise notice 'PASS: Learning authorship cannot be transferred'; end;
  begin perform public.folia_commit_document(alice,org,jsonb_set(doc,'{flashcards}',(doc->'flashcards')||jsonb_build_array(card||jsonb_build_object('id',gen_random_uuid(),'userId',alice))),1,gen_random_uuid()); raise exception 'Cross-author card accepted'; exception when check_violation then raise notice 'PASS: Members cannot add their own card to another author deck'; end;
  begin perform public.folia_commit_document('33333333-3333-4333-8333-333333333333',org,doc,1,gen_random_uuid()); raise exception 'Viewer edited notes'; exception when insufficient_privilege then raise notice 'PASS: Team viewers cannot mutate learning documents'; end;
  prefs:=public.folia_initialize_preferences(alice,org,doc->'preferences');
  perform pg_temp.assert_true(prefs->>'accentColor'='#654321' and prefs->'background'->>'kind'='none','New organization preferences inherit free custom accent but no personal paid background');
  perform pg_temp.assert_true((select payload=note from public.note_sheets where workspace_id=org),'Rejected cross-author changes leave original notes intact');
  update public.workspace_subscriptions set paid_through=now()-interval '1 second',status='canceled' where workspace_id=org;
  begin perform public.folia_commit_document(bob,org,jsonb_set(doc,'{noteSheets}',(doc->'noteSheets')||jsonb_build_array(note||jsonb_build_object('id',gen_random_uuid()))),1,gen_random_uuid()); raise exception 'New shared note accepted after Team expiry'; exception when insufficient_privilege then raise notice 'PASS: New shared organization notes require Team while personal notes remain Free'; end;
  doc:=jsonb_set(doc,'{noteSheets,0}',note||jsonb_build_object('content','Updated existing notes','revisions',jsonb_build_array(jsonb_build_object('title',note->>'title','content',note->>'content','editedAt',now()))));
  perform public.folia_commit_document(bob,org,doc,1,gen_random_uuid());
  perform pg_temp.assert_true((select payload->>'content'='Updated existing notes' from public.note_sheets where workspace_id=org),'Existing organization notes remain editable after Team expiry');
end $$;

set local role authenticated;
select set_config('request.jwt.claim.role','authenticated',true);
select set_config('request.jwt.claim.sub','33333333-3333-4333-8333-333333333333',true);
select pg_temp.assert_true((select count(*)=1 from public.note_sheets),'Viewer reads only permitted organization notes');
select pg_temp.assert_true((select count(*)=1 from public.flashcard_decks) and (select count(*)=1 from public.flashcards),'Viewer reads only permitted organization decks and cards');
do $$ begin
  begin update public.note_sheets set kind='note'; raise exception 'Direct note write succeeded'; exception when insufficient_privilege then raise notice 'PASS: Direct client note mutations denied'; end;
  begin delete from public.flashcards; raise exception 'Direct card delete succeeded'; exception when insufficient_privilege then raise notice 'PASS: Direct client card mutations denied'; end;
  begin perform private.commit_document_v1(auth.uid(),current_setting('test.org')::uuid,'{}',0,gen_random_uuid()); raise exception 'Old commit bypassed'; exception when insufficient_privilege then raise notice 'PASS: Legacy implementation cannot bypass new validation'; end;
  begin perform private.save_preferences_v1(auth.uid(),current_setting('test.org')::uuid,'{}',0,gen_random_uuid()); raise exception 'Old prefs bypassed'; exception when insufficient_privilege then raise notice 'PASS: Legacy preferences implementation is not client callable'; end;
end $$;
reset role;
delete from public.workspace_memberships where workspace_id=current_setting('test.org')::uuid and user_id='33333333-3333-4333-8333-333333333333';
set local role authenticated;
select pg_temp.assert_true((select count(*)=0 from public.note_sheets) and (select count(*)=0 from public.flashcards),'Membership revocation immediately removes learning read access');
reset role;
set local role service_role;
do $$ begin
  begin perform private.commit_document_v1(gen_random_uuid(),gen_random_uuid(),'{}',0,gen_random_uuid()); raise exception 'Old implementation callable'; exception when insufficient_privilege then raise notice 'PASS: Service role cannot directly bypass guarded document wrapper'; end;
end $$;
reset role;
set constraints all immediate;
rollback;
